require: rubocop-rails

Rails/ActionFilter:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/Output:
  Include:
  - app/**/*.rb
  - config/**/*.rb
  - db/**/*.rb
  - lib/**/*.rb
  - spec/**/*.rb

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLazyLookup:
  Enabled: false
