require: rubocop-rspec

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/AroundBlock:
  Enabled: false

RSpec/Be:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/BeEql:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

RSpec/ClassCheck:
  Enabled: false

RSpec/ContextMethod:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/DescribeSymbol:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/DescribedClassModuleWrapping:
  Enabled: false

RSpec/Dialect:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyHook:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWithoutDescription:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExcessiveDocstringSpacing:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ExpectOutput:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/Focus:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/InstanceSpy:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ItBehavesLike:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/OverwritingSetup:
  Enabled: false

RSpec/Pending:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ReceiveCounts:
  Enabled: false

RSpec/ReceiveNever:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/RepeatedIncludeExample:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SharedContext:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

RSpec/SingleArgumentMessageChain:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectDeclaration:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

RSpec/VariableDefinition:
  Enabled: false

RSpec/VariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

RSpec/Yield:
  Enabled: false
