linters:
  HexLength:
    enabled: false

  ImportantRule:
    enabled: false

  LeadingZero:
    style: include_zero

  NestingDepth:
    max_depth: 4

  PlaceholderInExtend:
    enabled: false

  PropertyCount:
    enabled: true

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    max_depth: 4

  SelectorFormat:
    convention: hyphenated_BEM
    ignored_names: ['form-control', 'modal-body', 'modal-content', 'modal-header', 'input-group', 'btn-gplus', 'btn-facebook', 'btn-twitter', 'btn-following']

  StringQuotes:
    style: double_quotes
